[build]
  functions = "backend/functions"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api*"
  to = "/.netlify/functions/api"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200